### ISSUE TITLE
`firstOrError` fails when subject immedieately complete

### ISSUE THREAD

**Issue by molikto** [badoo/Reaktive#433]
Code:

```
package molikto.apps

import com.badoo.reaktive.observable.firstOrError
import com.badoo.reaktive.observable.subscribeOn
import com.badoo.reaktive.scheduler.ioScheduler
import com.badoo.reaktive.scheduler.submit
import com.badoo.reaktive.single.subscribe
import com.badoo.reaktive.subject.publish.PublishSubject
import org.junit.Test


class ReactiveTest {

    @Test
    fun firstOrError() {
        val a = PublishSubject<Unit>()
        ioScheduler.submit {
            a.onNext(Unit)
            a.onComplete()
        }
        a.firstOrError().subscribe(onSuccess = {
        })
    }
}
```

result:

```
Exception in thread "main" java.util.NoSuchElementException
	at com.badoo.reaktive.observable.FirstOrErrorKt.firstOrError$default(FirstOrError.kt:5)
	at molikto.apps.ReactiveTest.firstOrError(ReactiveTests.kt:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
```

expected:

no exception

**Comment by arkivanov** [comment]
Hello, thanks for reporting the issue. You have race condition. Probably when you subscribe the item is already emitted. Since you are using PublishSubject there are no items buffered nor remembered. I will check.

**Comment by arkivanov** [comment]
@molikto I have checked the test, it passes on my machine for bot `JVM` and `linuxX64` targets. Although it may fail due to the race condition.

You can avoid the race condition for example this way:
```kotlin
    @Test
    fun firstOrError1() {
        val a = PublishSubject<Unit>()
        a.firstOrError().subscribe(
            onSubscribe = {
                ioScheduler.submit {
                    a.onNext(Unit)
                    a.onComplete()
                }
            },
            onSuccess = {
            }
        )
    }
```

**Comment by molikto** [comment]
You are right...
